trigger:
  branches:
    include:
      - main

variables:  
  ACR_NAME: 'crdevops12sem8'
  IMAGE_NAME: 'mybdmysql'
  SERVICE_CONNECTION_NAME: 'myappdevopssem08'

jobs:
  - job: BuildAndPush
    displayName: 'Construir y subir imagen MySQL al ACR'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Docker@2
        inputs:
          command: 'buildAndPush'
          containerRegistry: '$(SERVICE_CONNECTION_NAME)'
          repository: '$(IMAGE_NAME)'  
          dockerfile: '**/Dockerfile'
          tags: |
            latest
        displayName: 'Build and Push Docker Image to ACR'
